version: '3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan
    environment:
      - JUPYTER_TOKEN=secret
    command: start-notebook.sh
