version: '3'

services:
  jupyter:
    image: jupyter/minimal-notebook
    container_name: jupyter_notebook
    volumes:
      - ./pr3_logistic_regression/notebooks:/home/jovyan/pr3_logistic_regression
      - ./pr5_semantic_search/notebooks:/home/jovyan/pr5_semantic_search
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: secret